#!/bin/bash
cd /usr/local/php \
&& bin/php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
&& bin/php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
&& bin/php -r "unlink('composer-setup.php');" \

exit 0;