#!/bin/bash
cd /usr/local/php \
&& bin/php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
&& bin/php -r "if (hash_file('sha384', 'composer-setup.php') === 'e5325b19b381bfd88ce90a5ddb7823406b2a38cff6bb704b0acc289a09c8128d4a8ce2bbafcd1fcbdc38666422fe2806') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
&& bin/php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
&& bin/php -r "unlink('composer-setup.php');" \

exit 0;