#!/bin/bash

groupadd mysql \
&& useradd -r -g mysql -s /bin/false mysql \
&& git clone --single-branch --branch 5.7 https://github.com/mysql/mysql-server.git /root/src/mysql-server \
&& git clone https://github.com/pizdinad/boost_1_59_0.git /root/src/boost_1_59_0 \
&& cd /root/src/mysql-server \
&& mkdir bld_1 \
&& cd bld_1 \
&& cmake .. \
-DMYSQL_MAINTAINER_MODE=true \
-DWITH_NDBCLUSTER_STORAGE_ENGINE=OFF \
-DWITH_BOOST=/root/src/boost_1_59_0 \
&& make \
&& make install \
&& cd /usr/local/mysql \
&& mkdir mysql-files \
&& chown mysql:mysql mysql-files \
&& chmod 750 mysql-files \
&& bin/mysqld --initialize-insecure --user=mysql \
&& bin/mysql_ssl_rsa_setup --uid=mysql \
&& mkdir etc logs run tmp \
&& > ./logs/error.log \
&& chown mysql:www-data run \
&& chown mysql:mysql etc logs tmp ./logs/error.log \
&& chmod u=rwX,g=rX,o= run etc logs tmp ./logs/error.log \
&& git clone https://github.com/pizdinad/mysql-etc.git ./etc \
&& chmod o= ./etc/my.cnf \
&& ./support-files/mysql.server start \
&& bin/mysql -u root --skip-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root'; FLUSH PRIVILEGES;" \
&& ./support-files/mysql.server stop \

exit 0;
