#!/bin/bash

cd /root/src \
&& wget https://archive.apache.org/dist/httpd/httpd-2.4.29.tar.gz \
&& tar zxvf httpd-2.4.29.tar.gz \
&& cd httpd-2.4.29 \
&& ./configure \
--prefix=/usr/local/apache2 \
--enable-mpms-shared=all \
--enable-mods-shared=all \
--enable-suexec \
--with-suexec-bin=/usr/local/apache2/bin/suexec \
--with-suexec-caller=www-data \
--with-suexec-uidmin=30 \
--with-suexec-gidmin=30 \
--with-suexec-logfile=/usr/local/apache2/logs/suexec_log \
&& make \
&& make install \
&& cd /root/src \
&& wget http://apache-mirror.rbc.ru/pub/apache//httpd/mod_fcgid/mod_fcgid-2.3.9.tar.gz \
&& tar zxvf mod_fcgid-2.3.9.tar.gz \
&& cd mod_fcgid-2.3.9 \
&& APXS=/usr/local/apache2/bin/apxs ./configure.apxs \
&& make \
&& make install \
&& cd /usr/local/apache2 \
&& mv conf conf.default \
&& mkdir conf ssl.crt \
&& git clone https://github.com/pizdinad/apache2-conf.git ./conf \

exit 0;
